acme_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: AcmeSyliusExamplePlugin:Greeting:staticallyGreet
        name: ~

acme_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: AcmeSyliusExamplePlugin:Greeting:dynamicallyGreet
        name: ~

acme_sylius_example_cancel_gift_wrapping:
    path: /cart/gift-wrapping/cancel
    defaults:
        _controller: AcmeSyliusExamplePlugin:GiftWrapping:cancel
